### ISSUE TITLE
子应用按需加载无效

### ISSUE THREAD

**Issue by qiudongwei** [a1029563229/micro-front-template#28]
我留意到在首次加载某个子应用时，比如Vue主页，同时发起了其他子应用的资源请求，这导致子应用首次加载的白屏时间比较长，响应较慢（后续在各子应用之间切换无需再发起请求，切换响应比较迅速）。不能实现按需加载吗？未访问的子应用资源不加载。

**Comment by a1029563229** [comment]
1. 加载其他子应用是在当前子应用加载完成后，进行的预加载，并不会阻塞当前子应用的加载。
2. 可以通过 qiankun 的参数设置，修改预加载行为
