### ISSUE TITLE
'VueMicroApp' died in status LOADING_SOURCE_CODE: Failed to fetch"

### ISSUE THREAD

**Issue by junziyuyi** [a1029563229/micro-front-template#33]
请教一下 这种报错是什么原因 'VueMicroApp' died in status LOADING_SOURCE_CODE: Failed to fetch"

**Comment by wmo123** [comment]
你好，请问你的问题解决了吗？我也遇到了同样的问题

**Comment by wmo123** [comment]
我的问题解决了，是因为在微应用的配置文件中没有配置允许跨域

**Comment by a1029563229** [comment]
这个报错是获取不到子应用。

可能导致这个错误的原因有很多，要看一下详细报错。
