### ISSUE TITLE
yarn examples:install 报错

### ISSUE THREAD

**Issue by sonder022** [a1029563229/micro-front-template#77]
yarn run v1.22.10
$ npm-run-all --serial install:*
$ cd micro-app-main && yarn
error An unexpected error occurred: "Cannot create property 'program-files-nodejs-node-cache' on string '{\"program-files-nodejs-node-cache\":\"\"}'".
info If you think this is a bug, please open a bug report with the information provided in "D:\\VScode\\material\\素材\\work\\qiankun dom\\micro-front-template\\micro-app-main\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "install:main" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by liuJchun** [comment]
请问解决了吗，我也是报这个错

**Comment by liuJchun** [comment]
删除 所有yarn.lock 文件，重新安装 就可以了

**Comment by a1029563229** [comment]
已解决
